//
//  SpotifyASPatchStyleKit.swift
//  Spotify-AppleScript-Patch
//
//  Created by Boy van Amstel on 18/03/15.
//  Copyright (c) 2015 Danger Cove. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//



import Cocoa

public class SpotifyASPatchStyleKit : NSObject {

    //// Cache

    private struct Cache {
        static var actionColor: NSColor? = NSColor(calibratedRed: 0.506, green: 0.718, blue: 0.102, alpha: 1)
        static var actionColorHighlighted: NSColor? = SpotifyASPatchStyleKit.actionColor.shadowWithLevel(0.2)!
        static var actionColorDisabled: NSColor? = NSColor(calibratedRed: 0.622, green: 0.629, blue: 0.619, alpha: 1)
    }

    //// Colors

    public class var actionColor: NSColor { return Cache.actionColor! }
    public class var actionColorHighlighted: NSColor { return Cache.actionColorHighlighted! }
    public class var actionColorDisabled: NSColor { return Cache.actionColorDisabled! }

    //// Drawing Methods

    public class func drawRoundedButton(#frame: NSRect, withBackgroundColor: NSColor) {

        //// Rectangle Drawing
        let rectanglePath = NSBezierPath(roundedRect: NSMakeRect(frame.minX, frame.minY, frame.width, frame.height), xRadius: 8, yRadius: 8)
        withBackgroundColor.setFill()
        rectanglePath.fill()
    }

}
